INSERT INTO public.topic (id, topic, description) VALUES (1, 'Sport', 'Stay up-to-date with the latest sports news and analysis. Get live coverage, interviews, and more.');
INSERT INTO public.topic (id, topic, description) VALUES (2, 'Culture', 'Unleash your inner culture vulture! Stay informed about art, music, film, literature, and trends.');
INSERT INTO public.topic (id, topic, description) VALUES (3, 'Weather', 'Stay ahead of the weather with forecasts, breaking news, and expert analysis to plan your day.');
INSERT INTO public.topic (id, topic, description) VALUES (4, 'Technology', 'Explore the cutting-edge world of technology. Get updates on gadgets, innovations, and industry news.');
INSERT INTO public.topic (id, topic, description) VALUES (5, 'Politics', 'Stay informed about the latest political developments, elections, policies, and government news.');
INSERT INTO public.topic (id, topic, description) VALUES (6, 'Business', 'Get the latest business news, market updates, financial insights, and industry trends.');
INSERT INTO public.topic (id, topic, description) VALUES (7, 'Entertainment', 'Dive into the world of entertainment. Stay updated with celebrity news, movies, music, and more.');
INSERT INTO public.topic (id, topic, description) VALUES (8, 'Health', 'Stay healthy and informed with the latest medical breakthroughs, fitness tips, and wellness advice.');
INSERT INTO public.topic (id, topic, description) VALUES (9, 'Test', 'The only purpose of this topic is testing');
INSERT INTO public.topic (id, topic, description) VALUES (10, 'Lorem Lipsum', 'Updated for lorem tag');
INSERT INTO public.topic (id, topic, description) VALUES (12, 'secured', 'Create when secured');
INSERT INTO public.topic (id, topic, description) VALUES (13, 'secured2', 'Create when secured');
INSERT INTO public.topic (id, topic, description) VALUES (14, 'secured3', 'Create when secured');
INSERT INTO public.topic (id, topic, description) VALUES (15, 'secured3_2', 'Create when secured');
